### ISSUE TITLE
[Bug] Google Ads new api compatibility 

### ISSUE THREAD

**Issue by epkworkrise** [fivetran/dbt_google_ads#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am bringing up this bug because we have been informed that there is a New Google Ads API coming out and see that it will be different from the previous setup. I was wondering If and when the DBT hub package for this would be updated to accommodate the changes they are putting in place?

### Expected behavior

none

### dbt Project configurations

none

### Package versions

none

### What database are you using dbt with?

snowflake

### dbt Version

none

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as the solution is currently in place within the package. See the above comment for more details on how to leverage the Google Ads API version of the package.
