### ISSUE TITLE
[Bug] Spend is off due to Performance Max campaigns

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_google_ads#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hi there, we've started using Performance Max campaigns and noticed that they don't show up in the google ads reports.
They are captured in the new API but not picked up by this package as the they don't appear in the AD_STATS table which is the basis for other joins.

I'm wondering if there have been any considerations made around this already?  
Currently our marketing spend is off by the difference of the spend on Performance Max campaigns.

many thanks,
Christoph.

### Expected behavior

performance max campaign show up alongside other campaigns.  Spend on campaign matches what is shown in google portal.

### dbt Project configurations

1.1

### Package versions

latest

### What database are you using dbt with?

snowflake

### dbt Version

1.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann thanks so much for opening this issue.

This is actually a consideration we have been discussing as a team internally. At the moment you are correct that the package is built from the `ad_stats` table which a number of ads do not fall under. However, we have found that there are other source tables (like `campaign_stats`) where we have found some of these missing ads!

Fortunately enough, our team is in the process of adding more reporting functionality to our Ad packages and these types of considerations is one of them! Over the next two months we will be adding more flexibility to the packages and plan to account for these types of ads. I will be sure to keep you posted here as we build more of this functionality out.

It would be great as well if you would be willing to test any changes out to see if we capture all the ads on your end!

**Comment by leinemann** [comment]
This is great news, thank you @fivetran-joemarkiewicz !  I discovered a performance_max table that contained spot-on the according campaign data.  For our case that fitted in well as we only use the conversions as pass-through-metric.  But unfortunately our approach doesn't lent itself to be contributed back here as it would not work with other pass-through-metrics.  I'm very much looking forward to a bigger evolution that will allow for those other campaign types and by all means I'd be very happy to help testing and can't wait to return back to the open source version of the package again :-)

**Comment by fivetran-joemarkiewicz** [comment]
@leinemann that sounds great!! I will actually be working on the Google Ads upgrades in this coming sprint. I will post back here with details for you to test once it is ready 😄

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann the latest version of the Google Ads package should address the PMax campaign discrepancy you noted above. Using the google_ads__campaign_report should include the spend you are looking for!

As such, I will close this issue. However, please feel free to reopen if you feel there is more discussion to be had.
