### ISSUE TITLE
[Investigation] Databricks Hotfix for Ad Report Model

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [fivetran/dbt_google_ads#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The hotfix for this [PR](https://github.com/fivetran/dbt_google_ads/pull/37) needs to be investigated more in depth. For some reason, this package was passing in every warehouse in Buildkite except for Databricks. A hotfix was implemented so that integration testing can pass in order to not block [this PR](https://github.com/fivetran/dbt_ad_reporting/pull/70) for Ad Reporting. However, it is uncertain if the issue stemmed from the Databricks implementation or if the model(s) themselves should be updated. The hotfix was to move the Ad Report's join from using the history table for Ad ID to use the stats table for Ad ID. 

This ticket's purpose is to investigate this issue further and implement a long term fix for this issue. Whether that be updating the join logic such that we are pulling only from the respective stats tables for all of our models in this package (similar to Microsoft Ads), fixing the Databricks implementation or something else.

### Expected behavior

Details in the issue description.

### dbt Project configurations

dbt google ads 0.8.0

### Package versions

N/A

### What database are you using dbt with?

databricks

### dbt Version

1.3

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
we've figured this out (we did indeed need to pull the `stats` IDs rather than the history table ones due to Google hard-deleting entities from history tables but retaining them in the stats models 

https://github.com/fivetran/dbt_google_ads/pull/57
