### ISSUE TITLE
[Feature] Add PMAX campaigns to url report

### ISSUE THREAD

**Issue by hansottowirtz** [fivetran/dbt_google_ads#51]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

PMAX campaigns don't have ad groups and ads, but would it be possible to add them to the url report?

### Describe alternatives you've considered

For now we have custom logic to add the spend of the PMAX campaigns to the spend of the url report.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
Hi there @hansottowirtz thanks for opening this! Could you possibly share some of the logic you use to add PMAX campaigns into the url report? Code or just a high-level explanation would be much appreciated 

Also, I don't know much about PMAX campaigns, but why join them into the url report instead of the campaign-level report?

**Comment by fivetran-jamie** [comment]
Talked more about this with the team and they noted that in investigating [this previous issue](https://github.com/fivetran/dbt_google_ads/issues/31), we found that PMAX campaigns are only served at the campaign level and therefore can't be reflected in the URL, ad, or adgroup reports (at least not without muddying the model grain). 

So i am thinking that this may not be possible, unless we are missing something or Google has changed things in the past year 😞 @hansottowirtz

**Comment by fivetran-jamie** [comment]
going to close this out for now but please feel free to reopen if you'd like to continue discussing!
