### ISSUE TITLE
Null values in google_ads and ad_reporting_models

### ISSUE THREAD

**Issue by edwardskatie** [fivetran/dbt_google_ads#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Failure in test not_null_google_ads__keyword_report_criterion_id (models/google_ads.yml)
Failure in test not_null_ad_reporting__keyword_report_keyword_id (models/ad_reporting_models.yml)

### Expected behavior

There should no be nulls 

### dbt Project configurations

  - package: fivetran/ad_reporting
    version: 1.5.0

### Package versions

1.5.0

### What database are you using dbt with?

bigquery

### dbt Version

1.4

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-catfritz** [comment]
Hi @edwardskatie. Thanks for opening this issue! I agree with your fix and will be rolling it into our next release. The release may not be for a few more weeks, so I will send you a test branch of the latest version when it is ready and will keep you posted!

**Comment by fivetran-catfritz** [comment]
Hi @edwardskatie, we are now planning to incorporate this change into a patch release in the next week or so. If you are able to try it out, you can install it using the below code in your `packages.yml` in place of the normal google_ads lines. 
```yml
- git: https://github.com/fivetran/dbt_google_ads.git
  revision: bug/selected-join-table
  warn-unpinned: false
```
If you get to test it out, please let us know how it works for you!

**Comment by fivetran-catfritz** [comment]
This update has been incorporated into release v0.9.3! Closing out the issue.
